spring.application.name=auto_ecole



server.port=8081
# === CONFIG MYSQL ===
spring.datasource.url=jdbc:mysql://localhost:3306/autoecole?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=


# === CONFIG JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true


# JWT
jwt.secret=cleSecreteJWT123
jwt.expirationMs=86400000




# Logging
logging.level.org.springframework.security=DEBUG


